name: Selenium Tests

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Start test website
              run: npm run start-test-site &

            - name: Wait for server to start
              run: sleep 5

            - name: Set up Microsoft Edge
              uses: browser-actions/setup-edge@latest
              with:
                  edge-version: stable

            - name: Install MS Edge WebDriver
              run: |
                  EDGE_VERSION=$(microsoft-edge --version | cut -d ' ' -f 3 | tr -cd '0-9.')
                  echo "Edge version: $EDGE_VERSION"

                  # Get the clean driver version that matches Edge
                  DRIVER_VERSION=$(curl -s "https://msedgedriver.azureedge.net/LATEST_RELEASE_${EDGE_VERSION%%.*}")
                  echo "Driver version from release: $DRIVER_VERSION"

                  # Make sure we have a valid version number
                  if [[ ! "$DRIVER_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                    echo "Using latest stable driver instead"
                    DRIVER_VERSION=$(curl -s "https://msedgedriver.azureedge.net/LATEST_STABLE" | tr -cd '0-9.')
                  fi

                  echo "Final driver version: $DRIVER_VERSION"
                  DOWNLOAD_URL="https://msedgedriver.azureedge.net/${DRIVER_VERSION}/edgedriver_linux64.zip"
                  echo "Download URL: $DOWNLOAD_URL"

                  curl -Lo msedgedriver.zip "$DOWNLOAD_URL"
                  unzip msedgedriver.zip -d ./driver
                  chmod +x ./driver/msedgedriver
                  echo "./driver" >> $GITHUB_PATH

            - name: Run Selenium tests
              run: xvfb-run --auto-servernum npm test
              env:
                  SELENIUM_BROWSER: edge

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: test-results
                  path: reports/

            - name: Upload test logs
              uses: actions/upload-artifact@v4
              if: failure()
              with:
                  name: test-logs
                  path: |
                      ./logs
                      ./screenshots
